### ISSUE TITLE
JSYN, url is old

### ISSUE THREAD

**Issue by devxan** [Hans5958/userscripts#1]
JSYN, I checked out your website and the link to userscripts was an archived repo. (You recently commented that I had linked the wrong repo in a comment.) You might want to fix that. 🙂

**Comment by Hans5958** [comment]
> 
> 
> JSYN, I checked out your website and the link to userscripts was an archived repo. (You recently commented that I had linked the wrong repo in a comment.) You might want to fix that. 🙂

Sorry, I think you misunderstand. The one that was archived is [the scratch-userscripts repo](https://github.com/Hans5958/scratch-userscripts), which is the one you linked to, not [the userscripts repo](https://github.com/Hans5958/userscripts), which I linked earlier.

Also, who is the JSYN guy you referring to? I am known as Hans5958 in both Scratch and GitHub.

P/S: I have moved your issue on the userscript repo, just so you know.

**Comment by devxan** [comment]
> Also, who is the JSYN guy you referring to? I am known as Hans5958 in both Scratch and GitHub.

JSYN means "Just So You Know". 🙂

**Comment by Hans5958** [comment]
> 
> 
> > Also, who is the JSYN guy you referring to? I am known as Hans5958 in both Scratch and GitHub.
> 
> JSYN means "Just So You Know". 🙂

Oh, never heard that abbreviation. FYI would be a better term perhaps.

But still, you kind of confused about the two repos.

**Comment by devxan** [comment]
I don't think I am confused. Anyways, thanks for the advice! 🙂
