### ISSUE TITLE
Linkify

### ISSUE THREAD

**Issue by devxan** [Hans5958/userscripts#2]
Your linkify code doesn't work, so I have to use [Linkify Plus](https://greasyfork.org/en/scripts/2709-linkify-plus/code).

**Comment by Hans5958** [comment]
What do you mean? I used [this kind of Linkify library](https://github.com/Soapbox/linkifyjs), which still works until now.

**Comment by devxan** [comment]
@Hans5958 Well, when I downloaded your Linkify userscript, it didn't work.

**Comment by Hans5958** [comment]
Oh, okay. I found the issue. The Scratch's jQuery implementation is quite janky, so it is not working. I have created a solution that doesn't need jQuery in ScratchAddons, and I might consider to also do it here.

By the way, it's called "**More Links** in Scratch."
